server:
  port: 8080
spring:
  application:
    # App Name
    name: goddard_takeout
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://goddarddatabase.ccfiqqpxkqxy.us-east-2.rds.amazonaws.com:3306/goddard
      username: admin
      password: password321
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
goddard:
  path: D:\img\